# Generated by Django 4.1.6 on 2023-02-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='aunctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('prize', models.IntegerField()),
                ('pic', models.ImageField(upload_to='')),
            ],
        ),
    ]
