# Generated by Django 4.1.6 on 2023-02-12 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_aunctions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aunctions',
            new_name='Aunction',
        ),
    ]
