# Generated by Django 4.1.6 on 2023-02-12 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_aunctions_aunction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aunction',
            old_name='prize',
            new_name='price',
        ),
    ]
