# Generated by Django 4.1.6 on 2023-02-12 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_prize_aunction_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aunction',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=64),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=64)),
                ('aunction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onitem', to='auctions.aunction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.DecimalField(decimal_places=2, max_digits=64)),
                ('aunction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='auctions.aunction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lastbid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
