# Generated by Django 4.1.6 on 2023-02-13 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_rename_aunction_auction_rename_aunction_bid_auction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref', to='auctions.auction'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='auctions.auction'),
        ),
    ]
